-- Enable pgvector extension
create extension if not exists vector;

-- Profiles (synced from auth on first login)
create table if not exists profiles (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  full_name text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Projects
create table if not exists projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  name text not null,
  description text,
  blockchain_focus text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Project documents (generated by agents or uploaded)
create table if not exists documents (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  title text not null,
  doc_type text not null,
  content text,
  status text default 'draft',
  confidence_score float,
  sources jsonb,
  created_by text default 'agent',
  approved_by uuid references profiles(id),
  approved_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Inputs (Slack, Telegram, uploads, notes)
create table if not exists inputs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  source_type text not null,
  source_meta jsonb,
  raw_content text,
  storage_path text,
  processed boolean default false,
  created_at timestamptz default now()
);

-- Vector embeddings for RAG
create table if not exists embeddings (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  input_id uuid references inputs(id) on delete set null,
  document_id uuid references documents(id) on delete set null,
  chunk_text text not null,
  chunk_index int,
  embedding vector(1536),
  metadata jsonb,
  created_at timestamptz default now()
);

-- Chat messages
create table if not exists chat_messages (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  role text not null,
  content text not null,
  metadata jsonb,
  created_at timestamptz default now()
);

-- Agent audit log
create table if not exists agent_logs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  agent_type text not null,
  action text not null,
  input_summary text,
  output_summary text,
  confidence_score float,
  sources jsonb,
  approved boolean default false,
  approved_by uuid references profiles(id),
  created_at timestamptz default now()
);

-- Notifications
create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  project_id uuid references projects(id) on delete cascade,
  title text not null,
  body text,
  read boolean default false,
  action_url text,
  created_at timestamptz default now()
);

-- Integration configs (Slack, Telegram per project)
create table if not exists integrations (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  provider text not null,
  config jsonb not null,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes
create index if not exists idx_embeddings_project on embeddings(project_id);
create index if not exists idx_inputs_project on inputs(project_id);
create index if not exists idx_documents_project on documents(project_id);
create index if not exists idx_chat_project on chat_messages(project_id);
create index if not exists idx_notifications_user on notifications(user_id);
create index if not exists idx_projects_user on projects(user_id);
